// <auto-generated />
using System;
using Almostengr.GardenMgr.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Almostengr.GardenMgr.Migrations
{
    [DbContext(typeof(GardenDbContext))]
    [Migration("20220116163850_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Almostengr.GardenMgr.Api.Models.Observation", b =>
                {
                    b.Property<int>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HumidityPct")
                        .HasColumnType("REAL");

                    b.Property<double?>("PressureMb")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("REAL");

                    b.HasKey("ObservationId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Almostengr.GardenMgr.Api.Models.PlantWatering", b =>
                {
                    b.Property<int>("PlantWateringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantWateringId");

                    b.ToTable("PlantWaterings");
                });
#pragma warning restore 612, 618
        }
    }
}
